<a href="https://colab.research.google.com/github/onsoon829/dataproject/blob/master/200_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy
- NumPy는 Numerical Python의 줄임말로, 파이썬에서 산술 계산을 위한 가장 필수 패키지중 하나이다.
- 과학 계산을 위한 대부분의 패키지는 NumPy의 배열 객체를 데이터 교환을 위한 공통 언어처럼 사용한다.
- 효율적인 다차원 배열인 ndarray(n dimensional array)는 빠른 배열 계산과 유연한 브로드캐스팅 기능을 제공한다.
- 반복문을 작성할 필요 없이 전체 데이터 배열을 빠르게 계산할 수 있는 표준 수학 함수이다.
- 배열 데이터를 디스크에 쓰거나 읽을 수 있는 도구와 메모리에 적재된 파일을 다루는 도구이다.
- 선형대수, 난수 생성기등에 사용된다.
- C, C++, 포트란으로 작성한 코드를 연결할 수 있는 C API가 제공된다.


공식문서 https://numpy.org/doc/stable/  
numpy 100 문제 https://github.com/rougier/numpy-100

## 1. 데이터 생성

In [ ]:
# pip install numpy

import numpy as np

np.zeros() -> 모두 0 처리

In [ ]:
a = np.zeros(3) #1차원 배열 - 벡터
a

array([0., 0., 0.])

In [ ]:
print(dir(a))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '

In [ ]:
print(a.__repr__)

<method-wrapper '__repr__' of numpy.ndarray object at 0x7e66bc8d4450>


In [ ]:
print(a.__str__)

<method-wrapper '__str__' of numpy.ndarray object at 0x7e66bc8d4450>


In [ ]:
print(type(a))

<class 'numpy.ndarray'>


np.array()

In [ ]:
#1차원 배열 = 벡터
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [ ]:
print(a)
print(dir(a))
print(type(a))

[1 2 3]
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__redu

In [ ]:
#2차원 배열 = 행렬
b = np.array([[1, 2],[3, 4]]) #2행 2열
b

array([[1, 2],
       [3, 4]])

In [ ]:
print(b)
print(dir(b))
print(type(b))
print(b.shape) #현재 배열의 모양을 알고 싶다 -> shape

[[1 2]
 [3 4]]
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', 

In [ ]:
# 3차원 배열 이상 = 텐서(tensor)
c = np.array([[[[1,2],[3,4]],[5,7],[7,8]]]) # 2층(면, 공간), 2행, 2열

<ipython-input-25-fbc10a9528d6>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  c = np.array([[[[1,2],[3,4]],[5,7],[7,8]]]) # 2층(면, 공간), 2행, 2열


In [ ]:
print(c)
print(dir(c))
print(type(c))
print(c.shape)

[[[list([1, 2]) list([3, 4])]
  [5 7]
  [7 8]]]
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__rad

In [ ]:
a = np.array([1,2,3])
print(a)
print(a[0])

[1 2 3]
1


In [ ]:
#문자 데이터가 하나라도 있으면 전체가 문자로 바뀐다.
#numpy는 homogenous -> 같은 데이터 타입만 저장할 수 있다.
a = np.array([1,'2',3])
print(a)
print(a[0])

['1' '2' '3']
1


In [ ]:
a = np.array(['a',1,True])
print(a)
print(a[0])

['a' '1' 'True']
a


In [ ]:
a = np.array([0,False,1,True]) # False->0 True-> 1
print(a)
print(a[0])

[0 0 1 1]
0


np.zeros
 - tuple로 인자를 넣으면 그대로 모양을 만든다.
 - (2,3) : 2행 3열의 행렬을 만든다.
 - zeros는 기본값으로 0.으로 값을 모두 채운다.
   - np.zeros((2,3))
   - np.zeros([2,3])

In [ ]:
a = np.zeros(3)
print(a)
print(a.shape)

[0. 0. 0.]
(3,)


In [ ]:
a = np.zeros((2,3))
print(a)
print(a.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)


In [ ]:
a = np.zeros([2,3])
print(a)
print(a.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)


###np.eye
 - eye는 단위행렬
 - 숫자만 사용할 수 있다.

In [ ]:
a= np.eye(3) #3행 3열?
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#eye는 행과 열의 크기를 지정할 수 있다.
#3행 2열 행렬 생성
a = np.eye(3,2) #3행 2열
a

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [ ]:
#1을 시작뒤는 위치를 지정할 수 있다.(k=1)
a = np.eye(3, 4, k=1) #3행 4열
a

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### identity
 - 수학에서 단위행렬은 영어로 identity matrix
 - 크기 한 개만 지정해서 생성할 수 있다.

In [ ]:
a = np.identity(4)# 숫자에 따라 (그 숫자)행 (그 숫자)열로 출력값을 나타낸다.
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

###np full
 - 지정한 크기의 배열을 생성하고 채울 값을 지정한다.

In [ ]:
#2행 2열의 행렬을 생성하고 1로 초기화 해준다
a = np.full((2,2), 1) #np.full(shape, fill_value)
a

array([[1, 1],
       [1, 1]])

In [ ]:
#2행 2열의 행렬을 생성하고 각 행마다 1, 2로 초기화 해준다
a = np.full((2, 2), [1, 2])
a

array([[1, 2],
       [1, 2]])

In [ ]:
#2행 2열의 행렬을 생성하고 각 셀마다 1,2,3, 4로 초기화 해준다.
a = np.full((2, 2), [[1, 2],[3, 4]])
a

array([[1, 2],
       [3, 4]])

### np,empty
 - 배열을 생성하고 초기화를 지정하지 않는다.
 - 메모리에 있는 이나 이전에 사용했던 값들로 채워진다.

In [ ]:
a= np.empty(3)
a

array([0. , 0.5, 1. ])

In [ ]:
#2행 2열이 생성됨
a = np.empty((2,3))
a

array([[4.78724835e-310, 0.00000000e+000, 3.87347466e-321],
       [1.58101007e-322, 1.16904646e-313, 0.00000000e+000]])

### np.ones
 - 배열의 모든 값을 1로 채운다.

In [ ]:
a = np.ones(3)
a

array([1., 1., 1.])

In [ ]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

###_like
 - _like가 붙으면 shape이 같게 만들어진다.
 - 연산하기 위해서 shape을 맞춰야 하는 경우가 있다.

In [ ]:
#2행 3열의 배열 형성
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b = np.empty_like(a)
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
b = np.ones_like((a))
b

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
c = a + b
c


array([[2, 3, 4],
       [5, 6, 7]])

##linspace
 - 동등한 간격으로 값을 생성한다.
 - 0부터49까지 50개가 생성된다면 세 번째 num인자 값이 생략되어 있으므로 start와 end 계산해서 default 50이 생성된다.
 -

In [ ]:
a = np.linspace(0,5)
a

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [ ]:
# endpoint=False 설정하면 5가 표함이 안된다.
a = np.linspace(0, 5, endpoint=False)
a

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

###logspace
 - linspace와  비슷하다.
 -  log scale을 사용하는 차이가 있다.
 - 1부터 50까지 사이의 10개의 요소를 생성한다.

In [ ]:
np.logspace(1, 50, 10)

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

dtype

In [ ]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
print(type(a))
print(a.dtype) # int64 : 정수 64비트 => 8byte

<class 'numpy.ndarray'>
int64


In [ ]:
b = np.array([1,2,3], dtype=np.int8)
b

array([1, 2, 3], dtype=int8)

In [ ]:
#np.int8은 -128~127 사이의 값을 저장할 수 있다.
b = np.array([-128,-127,5,100,127], dtype=np.int8)
b

array([-128, -127,    5,  100,  127], dtype=int8)

In [ ]:
#np.int8은 -128~127 사이의 값을 저장할 수 있다.
# 128이 -128로 저장된다.(쓰레기 값)
b = np.array([-128,-127,5,100,128], dtype=np.int8)
b

array([-128, -127,    5,  100, -128], dtype=int8)

In [ ]:
#python의 int을 지정한다.
c = np.array([127,2, 3, -128],dtype=int) #int는 python의 데이터 타입이다.
c

array([ 127,    2,    3, -128])

In [ ]:
print(c.dtype) #python의 int ==numpy의 int64

int64


##python의 도움말
함수 뒤에 ? 붙이거나

In [ ]:
sum?

##numpy 도움말
 - np.lookfor(함수)

In [ ]:
np.lookfor('sum')

Search results for 'sum'
------------------------
numpy.sum
    Sum of array elements over a given axis.
numpy.cumsum
    Return the cumulative sum of the elements along a given axis.
numpy.einsum
    einsum(subscripts, *operands, out=None, dtype=None, order='K',
numpy.nansum
    Return the sum of array elements over a given axis treating Not a
numpy.nancumsum
    Return the cumulative sum of array elements over a given axis treating Not a
numpy.einsum_path
    Evaluates the lowest cost contraction order for an einsum expression by
numpy.trace
    Return the sum along diagonals of the array.
numpy.ma.sum
    Return the sum of the array elements over the given axis.
numpy.bool8.sum
    Scalar method identical to the corresponding array attribute.
numpy.polyadd
    Find the sum of two polynomials.
numpy.ma.cumsum
    Return the cumulative sum of the array elements over the given axis.
numpy.logaddexp
    Logarithm of the sum of exponentiations of the inputs.
numpy.bool8.cumsum
    Scalar

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
#array의 shape을 알려준다.
a.shape

(2, 3)

In [ ]:
# array이 몇 차원인지 안려준다.
a.ndim

2

In [ ]:
#array의 타입을 알려준다
a.dtype

dtype('int64')

In [ ]:

#요소의 개수를 알려준다.
#shape로도 알 수 있다.
a.size

6

In [ ]:
#요소당 byte수를 알려준다,
a.itemsize   #8bit = 1byte, 64bit = 8byte

8

##numpy와 python의 속도 차

In [ ]:
np.arange(10) #([start], [end], [step])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#numpy을 이용한 계산
%time np.sum(np.arange(100000000))

CPU times: user 204 ms, sys: 338 ms, total: 543 ms
Wall time: 604 ms


4999999950000000

In [ ]:
#python을 이용한 계산
%time sum(range(100000000))

CPU times: user 3.86 s, sys: 3.66 ms, total: 3.87 s
Wall time: 5.51 s


4999999950000000

같은 np.sum( )을 사용하더라도 값을 생성하는 방법에 따라 속도가 달라진다.

In [ ]:
%time np.sum(range(1000000000))

## copy

*대입문 6가지

a = 1

a = b = 1

a. *b = 1, 2, 3

a += 1

global, nolocal

python에서 copy

In [ ]:
a = [1,2,3]

In [ ]:
b = a

In [ ]:
b

[1, 2, 3]

In [ ]:
a is b #메모리 주소(=메모리) 비교

True

In [ ]:
#a와 b가 메모리 주소(=메모리)를 공유
#b값을 변경하면 a도 같이 변경이 된다.
b[0] = 7

In [ ]:
print(b)
print(a)

[7, 2, 3]
[7, 2, 3]


In [ ]:
a = [1,2,3]

In [ ]:
#copy()는 똑같은 값만 가지고 메모리(=메모리 주소)는 공유하지 않는다. 즉 deep copy가 된다.
b = a.copy() #copy메소드 호출

In [ ]:
a is b #is: 메모리 비교

False

In [ ]:
id(a)

134713534523328

In [ ]:
id(b)

134713533318976

In [ ]:
a == b #값 비교

True

In [ ]:
b[0] = 8
#a는 안바뀐다
print(a)
print(b)

[1, 2, 3]
[8, 2, 3]


In [ ]:
print(a is b)
print(a == b)

False
False


list가 2차원일때 copy

In [ ]:
a = [[1,2,3]]  #1차원

In [ ]:
type(a)

list

In [ ]:
#shallow copy (얕은 카피)
b = a.copy()

In [ ]:
print(a is b)  #메모리(=메모리 주소)
print(a == b)  #값 비교


False
True


In [ ]:
print(a[0])
print(b[0])

[1, 2, 3]
[1, 2, 3]


In [ ]:
b[0][0]= 10

In [ ]:
print(a[0] is b[0])
print(a[0] == b[0])

True
True


In [ ]:
import copy

In [ ]:
a = [1,2,3]
b = copy.deepcopy(a)  #list가 2차원일 때 deep copy를 하기 위해서 copy모듈에 있는 deepcopy메소드를 사용한다.

In [ ]:
print(a is b)  #메모리 주소(=메모리)
print(a == b)  #값 비교

True
True


In [ ]:
b[0][0]= 10

In [ ]:
print(a[0])
print(b[0])

[10, 2, 3]
[10, 2, 3]


In [ ]:
print(a[0] is b[0])
print(a[0] == b[0])

True
True


[:]는 전체라는 뜻이다.

슬라이싱 방식으로 1차 리스트일때는 재할당하면 deepcopy가 된다.

슬라이싱 방식으로 2차 리스트 이상인 경우는 shallow copy가 발생된다.

In [ ]:
a = [1,2,3]
b = a[:]

print(a is b)
print(a == b)

a = [1,2,3]
b = a[:]
print(a is b)
print(a == b)

print(a[0] is b[0])
print(a[0] == b[0])

False
True
False
True
True
True


In [ ]:
a = [256,2,3]
b = a[:]

print(a == b)
print(a is b)

print(a[0] == b[0])
print(a[0] is b[0])

True
False
True
True


In [ ]:
#intering
#파이썬은 느리기 때문에 중간에 cache 저장하는 기법이 있다
#-5에서 256은 파이썬에서 같은 메모리를 사용한다. (interning기법)
#문자열에서 a-zA-Z0-9는 내부적으로 interning기법을 사용한다.
m = 256
n = 256
print(m is n)

m = 257
n = 257
print(m is n)

True
False


In [ ]:
k = 'python'
p = 'python'
print(k is p)

True


In [ ]:
#1차원: 값 비교
#2차원: 메모리(=메모리 주소), 값 비교

##정리

In [ ]:
a = [[1, 2, 3]], [[4, 5, 6]] #python에서 제공하는 데이터 타입인 list
b = a

print(a is b)
print(a == b)

a[0][0] = 10
print(a is b)
print(a == b)

c = a.copy()
print(a is c)
print(a == c)

a[0][0] = 20
print(a is c)
print(a == c)

print(a[0])

True
True
True
True


AttributeError: ignored

In [ ]:
d[0][0] = 30
print(d is a)
print()

In [ ]:
#c = copy()     =     c = [:] 두 식이 같다

##numpy에서 copy

In [ ]:
import numpy as np

In [ ]:
a = b = np.array([1,2,3])

In [ ]:
print(a is b)
print(a == b) #

True
[ True  True  True]


In [ ]:
a[0] #indexing

1

In [ ]:
a[:] #slicing

array([1, 2, 3])

In [ ]:
a[0] = 100
print(a[0])
print(b[0])

100
100


array는 homogeneous, sequence, mutable 이다.
list는 heterogeneous, sequence, mutable이다




In [ ]:
a = np.array([1,2,3])#numpy는 기본적으로 deepcopy가 발생
b = a.copy()

print(a is b)
print(a == b)

False
[ True  True  True]


In [ ]:
print(a[0] is b[0])

False


### as 계열
다른 데이터 타입을 가져와 바꿔서 사용할 때는 as라는 이름이 보통 붙는다.

In [ ]:
a = [1.4, 2.5, 3.5]
b = np.array(a)

print(type(a))
print(type(b))
print(type(a[0]))
print(type(b[0]))

<class 'list'>
<class 'numpy.ndarray'>
<class 'float'>
<class 'numpy.float64'>


In [ ]:
a = [1.4, 2.5, 3.5]
b = np.asarray(a)

print(type(a))
print(type(b))
print(type(a[0]))
print(type(b[0]))

<class 'list'>
<class 'numpy.ndarray'>
<class 'float'>
<class 'numpy.float64'>


In [ ]:
a = [1, 2, 3]
b = np.asfarray(a)

print(type(a))
print(type(b))
print(type(a[0]))
print(type(b[0]))

<class 'list'>
<class 'numpy.ndarray'>
<class 'int'>
<class 'numpy.float64'>


###값 가져오기

####(1) 인덱싱, 슬라이싱 방법 가능

In [ ]:
a = [[1,2,3], [4,5,6]] #python의list
b = np.array([[1,2,3],[4,5,6]]) #numpy의 array

In [ ]:
print(a[0])
print(b[0])

[1, 2, 3]
[1 2 3]


In [ ]:
print(type(a[0]))
print(type(b[0]))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
#print(a[0,1]) # TypeError: list indices must be integers or slices, not tuple
print(a[0][1])
print(b[0,1]) # array

2
2


In [ ]:
#list에서의 copy 방식과 numpy배열에서의 copy 방식이 다르다.

In [ ]:
print(a[slice(0,1)])# 0행부터 1행 미만의 데이터를 가져온다, 2차원이 유지된다.
print(a[0]) # 1차원으로 가져온다.

print(type(a[slice(0,1)]))
print(type(a[0]))

[[1, 2, 3]]
[1, 2, 3]
<class 'list'>
<class 'list'>


numpy는 기본적으로 인덱싱/슬라이싱할 때 comma를 사용할 수 있다.

In [ ]:
print(type(b))
print(b[0,1]) #b[행,열]    indexing
print(b[0][1]) #b[행],[열] indexing
print(b[0, -1]) #          indexing
print(b[0:1, 0:2])#        slicing  [[1 2]]
print(b[0:2, 0:2])#        slicing [[1 2][4 5]]

<class 'numpy.ndarray'>
2
2
3
[[1 2]]
[[1 2]
 [4 5]]


In [ ]:
#python
print(type(a))
print(a[0][1])  #a[행][열]  indexing
print(a[0:1]) # [[1, 2, 3]] slicing 후후후
print(a[0:1][0:1])
print(a[1:2])
print(a[0:2, 0:2])

<class 'list'>
2
[[1, 2, 3]]
[[1, 2, 3]]
[[4, 5, 6]]


TypeError: ignored

####(2) boolean indexing

In [ ]:
a = [[1,2,3], [4,5,6]]

In [ ]:
print(type(a))
print(a*3)
a>3 #다른 타입의 함수는 비교 불가능

<class 'list'>
[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]


TypeError: ignored

In [ ]:
b = np.array([[1,2,3,4]]) #numpy array
c = np.array([[2,2,2,2]]) #numpy array

In [ ]:
b > c

array([[False, False,  True,  True]])

array는 scarlar와 연산하면 elementwise로 계산한다.

(elementwise: 원소별로 각각 계산이 된다.)

In [ ]:
b > 2

array([[False, False,  True,  True]])

In [ ]:
b[np.array([[False, False, True, True]])]

array([3, 4])

In [ ]:
b[b>2] # = np.array([False, False, True, True])

array([3, 4])

num에서 boolean indexing 조건
 - array만 가능하다.
 - numpy True, False로만 가능하다.
 - shape가 맞아야 한다.(개수가 맞을 때만 사용할 수 있다)

In [ ]:
#python에서는 boolean indexing을 지원 안한다.
a = [[1,2,3,4]]
a[[False,False,True,True]]

TypeError: ignored

(3) fancy indexing


In [ ]:
#np.arange([start,] end [, step])
#reshape(행 갯수, 열 갯수): 배열의 구조 변경
#a = np.arange(100)
#b = a.reshape(20, 5)
#print(a.shape)
#print(b.shape)

b = np.arange(100).reshape(20, 5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [ ]:
print(b[:]) #전체를 가져온다. b[:,:]와 같다
print([1,3]) # b[행, 열]
print(b[1:3, 2:4])  # 1행부터 3행미만, 2열부터 4열미만의 데이터를 가져온다.
print(b[[1,3,5],[0,2,4]]) #1행 0열, 3행 2열, 5행 4열의 데이터를 가져온다.
print(b[[1,3,5]]) #1행, 3행, 5행의 데이터를 가져온다.


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]
[1, 3]
[[ 7  8]
 [12 13]]
[ 5 17 29]
[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [25 26 27 28 29]]
[[ 0  2  4]
 [ 5  7  9]
 [10 12 14]
 [15 17 19]
 [20 22 24]
 [25 27 29]
 [30 32 34]
 [35 37 39]
 [40 42 44]
 [45 47 49]
 [50 52 54]
 [55 57 59]
 [60 62 64]
 [65 67 69]
 [70 72 74]
 [75 77 79]
 [80 82 84]
 [85 87 89]
 [90 92 94]
 [95 97 99]]


In [ ]:
print(b[[1,3,4], [0,2]]) #행과 열의 갯수를 같게 지정해야 한다.
print(b[[:],[1,2,3]]) # fancy indexing에서는 슬라이싱 못 쓴다(2)



IndexError: ignored

In [ ]:
print(b[[1,3,4],[0]])

[ 5 15 20]


In [ ]:
m = np.arange(1,9).reshape(2,4) #일단 보류
#n = np.array([2])        #(1,)
n = np.array([[2]])       #1,1
n = np.array([[1,2,3,4]]) #(1,4)
#n = np.array([1,2,3,4])  #(4,)
#n = np.array[[1][1]]     #(2,1)
print(m)
print(m.shape)
print(n)
print(n.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1 2 3 4]]
(1, 4)


In [ ]:
m + n

array([[ 3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14]])

##3차원 이상에서 차원 구별하는 법

In [ ]:
#0에서 24미만까지 생성
b = np.arange(24).reshape(2,3,4) #3차원 (2층(면), 3행, 4열)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
b[0] #2차원으로 반환

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b[0][0] #1차원으로 반환

array([0, 1, 2, 3])

In [ ]:
b[1,1] #1공간(층, 면) 1행


array([16, 17, 18, 19])

In [ ]:
b[:, 1, 3] #0공간 1행 3열

array([ 7, 19])

In [ ]:
b[:,:,1] #모든 공간(층), 모든 행의 1번째 열 뽑아라

array([[ 1,  5,  9],
       [13, 17, 21]])

###fancy indexing와 indexing 차이
 - indexing은 원래 차원에서 하나 감소해서 가져오고 fancy indexing은 원래 차원 그대로 가져온다,

In [ ]:
#indexing은 차원이 하나 감소해서 가져온다.(3차원을 2차원으로 가져온다)
b[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#fancy indexing은 원래 3차원 그대로 가져온다,
b[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#b[0]은 b[0,:,:]의 단축표현이다.

### Ellipsis

...(Ellipsis)는 이후로 모든 것을

SyntaxError: ignored

In [ ]:
[[0]

### Ellipsis

...(Ellipsis)는 이후로 모든 것을 의미한다.

In [ ]:
#b[0] = b[0,:,:] = b[0...]
b[0]#생략기법
b[0,:,:] # slicing 기법
b[0,...]# ellipsis 기법

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
type(...)

ellipsis

In [ ]:
# 숫자 1,5,9만 가져온다.
b[0, :, [1]]

array([[1, 5, 9]])

In [ ]:
# 숫자 1,5,9,3,7,11 가져오기
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
b[0, :, [1,3]]

array([[ 1,  5,  9],
       [ 3,  7, 11]])

In [ ]:
#숫자 4,5,6,7,16,17,18,19 가져오기
b[:,1 ,:]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [ ]:
#숫자 3,7,11,15,19,23 가져오기
b[:,:, 3]

array([[ 3,  7, 11],
       [15, 19, 23]])

In [ ]:
b[:, :, 3:4] #3차원으로 가져옴

array([[[ 3],
        [ 7],
        [11]],

       [[15],
        [19],
        [23]]])

In [ ]:
b[:, :, [3]] #3차원으로 가져옴

array([[[ 3],
        [ 7],
        [11]],

       [[15],
        [19],
        [23]]])

##줄임표현(...)

출력해야 할 데이터 수가 엄청 클 때 보이는 ...은 ellipsis와 다르다,

In [ ]:
#out에 나오는 ...은 단순히 줄임표현이다,
np.arange(10000)

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [ ]:
#...양쪽으로 출력 갯수 지정
np.set_printoptions(edgeitems=6)

In [ ]:
np.arange(10000)

array([   0,    1,    2,    3,    4,    5, ..., 9994, 9995, 9996, 9997,
       9998, 9999])

## 연산
numpy 연슨의 기본은 두 개의 shape가 같아야 한다,

In [ ]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a.shape

(3, 4)

In [ ]:
b = np.arange(1, 13).reshape(3,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b.shape

(3, 4)

numpy는 elementwise로 vectorize 연산을 한다.

vectorize는 데이터의 연산을 이로갈적으로 처리하는 기능이다.



In [ ]:
#같은 위치의 원소끼리 더해 준다.(elementwise)
a + b

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [ ]:
#python의 list에서 +연산자는 elementwise가 아니라 list를 확장시킨다.(연결)
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [ ]:
@np.vectorize
def plus(a,b):
  return a+b

plus([1,2,3], [4,5,6])

[1, 2, 3, 4, 5, 6]

In [ ]:
b = np.arange(6,12).reshape(2,3)
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
a * b #elementwise

array([[ 36,  49,  64],
       [ 81, 100, 121]])

In [ ]:
#python에서 list끼리 *(곱하기)를 할 수 없다.
[1,2,3] * [4,5,6]

TypeError: ignored

In [ ]:
c = np.matrix([[1,2],[3,4]])  #행렬 생성
c

matrix([[1, 2],
        [3, 4]])

In [ ]:
type(c)

numpy.matrix

In [ ]:
print(c)
c * c
#1*1 + 2*3=7      1*2 + 2*4=10
#3*1 + 4*3=15      3*2 + 4*4=22

# 행렬 곱하기할 때 앞의 행과 뒤의 열의 갯수가 같아야 한다.

[[1 2]
 [3 4]]


matrix([[ 7, 10],
        [15, 22]])

ndarray에서 행렬 곱 연산자 @이다?

python에서 제공한다.-> python재단에서 numpy를 위해 만들어준 장치이다

T는 transpose(전치)의 약자이다.

In [ ]:
aT

NameError: ignored

In [ ]:
print(a)
print(a.shape)

[[1, 2, 3], [4, 5, 6]]


AttributeError: ignored

In [ ]:
print(a.T)
print(a.T.shape) # 계산(3,3) 결과(2,2)
#(3,4)(4,2) => 결과(3,2)
#(2,3)(3,5) => 결과(2,5)

[[ 6  9]
 [ 7 10]
 [ 8 11]]
(3, 2)


In [ ]:
c @ c. T

matrix([[ 5, 11],
        [11, 25]])

In [ ]:
a = arange(1, 17).reshape(1,16)

NameError: ignored

In [ ]:
print(a.shape)    #(1, 16)
print(a.T.shape)  #(16, 1)
a @ a.T           #결과(1,1)

AttributeError: ignored

matrix는 *와 @ 모두가 가능하다.

In [ ]:
c * c.T

matrix([[ 5, 11],
        [11, 25]])

In [ ]:
c @ c.T

matrix([[ 5, 11],
        [11, 25]])

함수방법으로 np.dot() 함수를 사용할 수 있다.

In [ ]:
np.dot(a, a.T)

AttributeError: ignored

In [ ]:
print(type(c))

<class 'numpy.matrix'>


* : matrix

@: matrix, ndarray

dot(): matrix, ndarray

method 방식으로 행렬곱 할 수 있다.
function방법과 사용하는 방법이 다르므로 주의한다.

In [ ]:
np.dot(c, c.T) #numpy에서 제공된 function 함수로 쓴 것

matrix([[ 5, 11],
        [11, 25]])

In [ ]:
c.dot(c.T)  #method 방식으로 쓴 것

matrix([[ 5, 11],
        [11, 25]])

## strides
strides는 다음 원소끼리의 메모리 크기를 차원별로 알려준다,

c의 포인터 개념을 알고 있으면 이해하기가 쉽다. 포인터?

In [ ]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#행의 메모리 간격은 32bytes
#열의 메모리 간격은 8bytes
a.strides


(32, 8)

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.itemsize

8

In [ ]:
#열의 원소 갯수 * itemsize = 행의 메모리간격
#itemsize = 열의 메모리간격

axis

axis는 다차원 배열을 연산할 때 기준이 되는 축이다.

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.sum(a)

66

In [ ]:
np.sum(a, axis=0) #행을 기준으로 더하라. a배열은 2차원이므로 axis=0은 행기준(행마다)

array([12, 15, 18, 21])

(0,0)(0,1)(0,2)(0,3)

(1,0)(1,1)(1,2)(1,3)

(2,0)(2,1)(2,2)(2,3)

열 행

In [ ]:
np.sum(a, axis=1)  #a배열은 2차원이므로 axis=0은 열기준(열마다)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [ ]:
a = np.arange(24).reshape(2,3,4) #2공간(층, 면) 3행 4행
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

(0,0,0) (0,0,1) (0,0,2) (0,0,3)

(0,1,0) (0,1,1) (0,1,2) (0,1,3)

(0,2,0) (0,2,1) (0,2,2) (0,2,3)


(1,0,0) (1,0,1) (1,0,2) (1,0,3)

(1,1,0) (1,1,1) (1,1,2) (1,1,3)

(1,2,0) (1,2,1) (1,2,2) (1,2,3)

열 행

In [ ]:
np.sum(a) #(2,3,4) =>(1,)

276

In [ ]:
np.sum(a, axis=0)  #(2,3,4) =>(3,4) #공간기준(공간마다)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [ ]:
np.sum(a, axis=1) #(2,3,4)=>(2,4) #행기중(행마다)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [ ]:
np.sum(a, axis=2) #(2,3,4) =>(2,3)#열기준(줄임말())

array([[ 6, 22, 38],
       [54, 70, 86]])

##array 모양 바꾸기


(1) reshape
reshape는 차원을 바꿔주는 기능을 한다.

In [ ]:
a= a.reshape(3,8)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
#ValueError =. 크기가 맞지 않음
b = a.reshape(2,3,5)
b

ValueError: ignored

In [ ]:
#음수를 쓰면, 알아서 shape를 맞춘다.
#음수값은 아무거나 상관없다
b = a.reshape(2, 3, -1)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
b = a.reshape(3,5,-1)
b

NameError: ignored

In [ ]:
b = a.reshape(3,-1,2)
b

NameError: ignored

In [ ]:
b = a.reshape(-1,3,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

(2)reshape로 차원 늘리기

In [ ]:
#2차원
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

resize

size의 원소 개수를 알려준다.

In [ ]:
a = np.arange(24)
print(a.size)
print(len(a))

24
24


In [ ]:
# mutable이다. return이 없고 자기 자신을 바꾼다. ->reshape와 차이점1
#원래의 원소 개수와 변경하는 원소 개수가 안맞아도 된다.(0으로 채워준다.)=>reshape와 차이점 2
b = np.arange(24)
b.resize(2,3,8)
b

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]],

       [[ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0]]])

In [ ]:
#원래의 원소 개수보다 작으면 버린다.
b = np.arange(24)
b.resize(2,3,2)
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

array 쪼개기

split

In [ ]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
a = np.split(a, 3, axis=0)
print(a)
print(type(a))

[array([0, 1, 2, 3, 4, 5, 6, 7]), array([ 8,  9, 10, 11, 12, 13, 14, 15]), array([16, 17, 18, 19, 20, 21, 22, 23])]
<class 'list'>


In [ ]:
b = np.split(a, 3, axis=0)
print(b)
print(type(b)) #list

[array([0, 1, 2, 3, 4, 5, 6, 7]), array([ 8,  9, 10, 11, 12, 13, 14, 15]), array([16, 17, 18, 19, 20, 21, 22, 23])]
<class 'list'>


In [ ]:
#1차원일 때는 axis=1을 사용할 수 없다. (차원이 다르니까?)

In [ ]:
#0부터 5미만 인덱스
#5이상 8미만 인덱스
#8이상 13미만 인덱스
#13이상
np.split(a, [5, 8, 13])#0~5미만, 5~8미만, 13이상

[array([0, 1, 2, 3, 4]),
 array([5, 6, 7]),
 array([ 8,  9, 10, 11, 12]),
 array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])]

hsplit & vsplit

In [ ]:
a = np.arange(24)
b = a.reshape(4,6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
np.split(b, 2, axis=0) #b는 2차원이므로 axis=0의 의미는 행이다.

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

In [ ]:
#2차원이므로 axis=1을 사용할 수 없다?
np.split(b, 2, axis=1)# b는 2차원이므로 axis=1의 의미는 열이다.

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]])]

In [ ]:
#vertical
np.vsplit(b, 2) #np.split(b, 2, axis=0)와 같다.

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

In [ ]:
#horizental(수평)
np.hsplit(b,2) #np.split(b, 2, axis=1)와 같은 결과이다.

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]])]

In [ ]:
c = np.arange(6)
c

array([0, 1, 2, 3, 4, 5])

In [ ]:
#2차원 이상일때만 사용할 수 있다
np.vsplit(c, 2) #vsplit only works on arrays of 2 or more dimensions

ValueError: ignored

In [ ]:
#hsplit()은 1차원일때도 가능하다.
np.hsplit(c, 2)
c

array([0, 1, 2, 3, 4, 5])

array 합치기

In [ ]:
a = np.arange(24)
x, y, z = np.split(a,3)


In [ ]:
print(x)
print(y)
print(z)

[0 1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14 15]
[16 17 18 19 20 21 22 23]


hstack & vstack

In [ ]:
#hstack은 horizenal(가로)로 합쳐준다
np.hstack((x,y))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
#vstack은 vertical(세로)로 합쳐준다.
np.vstack((x,y))#튜플로 합친다?

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

dstack
 - destack은 합쳐서 3차원으로 만들어준다.
 - 합칠 array들이 1차원, 2차원일 경우 차원을 늘린 후 합친다.
 - 합쳐지는 차원은 axis=2이다.

In [ ]:
#x는 shape 1차원이므로 (1, m, 1)인 3차원 변환한다.
#y는 shape 1차원이므로 (1, n, 1)인 3차원 변환한다.
c = np.dstack((x,y))
c

array([[[ 0, 10],
        [ 1, 11]],

       [[ 2, 12],
        [ 3, 13]],

       [[ 4, 14],
        [ 5, 15]],

       [[ 6, 16],
        [ 7, 17]],

       [[ 8, 18],
        [ 9, 19]]])

In [ ]:
c.shape  #2열

(5, 2, 2)

In [ ]:
x = np.arange(10).reshape(5,2)  #1~9까지의 범위, 5행 2열로 나눠라.
y = np.arange(10, 20).reshape(5,2) #10~19까지의 범위, 5행 2열로 나눠라.
print(x)
print(y)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [ ]:
c = np.dstack((x,y)) # x, y 합치기
print(c)
c

[[[ 0 10]
  [ 1 11]]

 [[ 2 12]
  [ 3 13]]

 [[ 4 14]
  [ 5 15]]

 [[ 6 16]
  [ 7 17]]

 [[ 8 18]
  [ 9 19]]]


array([[[ 0, 10],
        [ 1, 11]],

       [[ 2, 12],
        [ 3, 13]],

       [[ 4, 14],
        [ 5, 15]],

       [[ 6, 16],
        [ 7, 17]],

       [[ 8, 18],
        [ 9, 19]]])

In [ ]:
c.shape #5행 2열 2개씩

(5, 2, 2)

#### concatenate
 - concate는 axis 방향에 그대로 합쳐준다.
 - stack은 axis방향에 새로운 차원을 만들어 합쳐준다.

In [ ]:
a = np.arange(12).reshape(3,4) #0~11까지 범위, 3행 4열
x, y = np.split(a, 2, axis = 1) #a를 가지고 2열 1축

print(a)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1]
 [4 5]
 [8 9]]
[[ 2  3]
 [ 6  7]
 [10 11]]


In [ ]:
#np.split(a, 2, axis = 1)
np.stack((x,y)) #2차원인데 차원이 증가해서 3차원을 생성한다.

array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[ 2,  3],
        [ 6,  7],
        [10, 11]]])

In [ ]:
#원래 shape 크기 그대로 유지를 한다. 즉 2차원이 그대로 유지된다.
np.concatenate((x,y)) #axis=0 default

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [ 2,  3],
       [ 6,  7],
       [10, 11]])

##차원확장

stack

In [ ]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#tuple에 원소가 1개 있으면 차원만 확장시켜준다.
np.stack((a,)) # 차원 증가

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

newaxis

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a[np.newaxis,:,:]


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [ ]:
a[np.newaxis,:,:].shape

(1, 3, 4)

In [ ]:
#행 추가
a[:, np.newaxis, :]

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [ ]:
a[:, np.newaxis, :].shape

(3, 1, 4)

In [ ]:
#열 추가
a[:, :, np.newaxis]

array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]]])

In [ ]:
a[:, :, np.newaxis].shape

(3, 4, 1)

np.newaxis 대신에 None을 써도 된다.

None은 직관적이지 않고 헷갈려서 np.newaxis를 만들었다.

In [ ]:
np.newaxis is None

True

In [ ]:
a[:, :, None]

array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]]])

expand_dims

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.expand_dims(a, axis=0) #a[np.newaxis, :, :]와 같다

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [ ]:
np.expand_dims(a, axis=1) #a[:, np.newaxis, :]와 같다

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [ ]:
np.expand_dims(a, axis=2) #a[:, :, np.newaxis]와 같다

array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]]])

### array한 줄로 펴기

flatten

In [ ]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b = a.flatten()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
b.shape

(12,)

#### 서로 차원 교환

swapaxes

In [ ]:
a = np.array([[1],[2]]) #2행 1열
a

array([[1],
       [2]])

In [ ]:
b = np.swapaxes(a, 1, 0) #1축과 0축을 바꾸겠다. 1: 열, 0: 행을 의미하므로 행 열의 자리를 바꾼다.
b

array([[1, 2]])

In [ ]:
b.shape #1행 2열

(1, 2)