<a href="https://colab.research.google.com/github/onsoon829/dataproject/blob/master/400_pandas_%EA%B8%B0%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## version

프로젝트 할 때는 버젼을 맞춰서 해야 한다.

In [ ]:
# python
import sys
print(sys.version)

!python --version

3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Python 3.10.12


In [ ]:
#numpy
import numpy as np
print(np.__version__)

1.23.5


In [ ]:
#pandas
import pandas as pd
print(pd.__version__)

1.5.3


In [ ]:
#google colab
!pip freeze

absl-py==1.4.0
aiohttp==3.8.6
aiosignal==1.3.1
alabaster==0.7.13
albumentations==1.3.1
altair==4.2.2
anyio==3.7.1
appdirs==1.4.4
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
array-record==0.5.0
arviz==0.15.1
astropy==5.3.4
astunparse==1.6.3
async-timeout==4.0.3
atpublic==4.0
attrs==23.1.0
audioread==3.0.1
autograd==1.6.2
Babel==2.13.1
backcall==0.2.0
beautifulsoup4==4.11.2
bidict==0.22.1
bigframes==0.13.0
bleach==6.1.0
blinker==1.4
blis==0.7.11
blosc2==2.0.0
bokeh==3.3.1
bqplot==0.12.42
branca==0.7.0
build==1.0.3
CacheControl==0.13.1
cachetools==5.3.2
catalogue==2.0.10
certifi==2023.7.22
cffi==1.16.0
chardet==5.2.0
charset-normalizer==3.3.2
chex==0.1.7
click==8.1.7
click-plugins==1.1.1
cligj==0.7.2
cloudpickle==2.2.1
cmake==3.27.7
cmdstanpy==1.2.0
colorcet==3.0.1
colorlover==0.3.0
colour==0.1.5
community==1.0.0b1
confection==0.1.3
cons==0.4.6
contextlib2==21.6.0
contourpy==1.2.0
cryptography==41.0.5
cufflinks==0.17.3
cupy-cuda11x==11.0.0
cvxopt==1.3.2
cvxpy==1.3.2
cycler==0.12.1
cy

## 구글 드라이브 연동

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

%cd  '/content/drive/MyDrive/ai_chat_python'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive/ai_chat_python


## 파일 형식 데이터 불러오기

In [ ]:
print(dir(pd))
print(type(pd))

['ArrowDtype', 'BooleanDtype', 'Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Flags', 'Float32Dtype', 'Float64Dtype', 'Float64Index', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int64Index', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NA', 'NaT', 'NamedAgg', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseDtype', 'StringDtype', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt64Index', 'UInt8Dtype', '__all__', '__builtins__', '__cached__', '__deprecated_num_index_names', '__dir__', '__doc__', '__docformat__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_config', '_is_numpy_dev', '_libs', '_testing', '_typing', '_version', 'annotations', 'api', 'array', 'arrays', 'bd

In [ ]:
#header라는 키워드를 지정하지 않고 호출했을때 무조건 파일의 첫줄을 header로 처리한다.
data = pd.read_csv('./source/num.txt')
print(data)

   1  2  3  4   5
0  6  7  8  9  10


In [ ]:
# 읽어올 파일에 header가 없으면 header=None을 지정한다.
# 그렇지 않으면 첫번째 줄을 컬러명으로 처리한다.
#header파라미터의 default: 'infer'이다.
data = pd.read_csv('./source/num.txt', header=None)
print(data)

   0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10


In [ ]:
print(type(data))     # 'pandas.core.frame.DataFrame
print(dir(data))

<class 'pandas.core.frame.DataFrame'>
['T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__contains__', '__copy__', '__dataframe__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__

In [ ]:
print(data[0])        # data.컬럼명[열]
print(type(data))     # 'pandas.core.frame.DataFrame
print(dir(data))

0    1
1    6
Name: 0, dtype: int64
<class 'pandas.core.frame.DataFrame'>
['T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__contains__', '__copy__', '__dataframe__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__redu

In [ ]:
print(data.iloc[0])                 # data.iloc[index(행)]
print(type(data.iloc[0]))           #pandas.core.series.Series

0    1
1    2
2    3
3    4
4    5
Name: 0, dtype: int64
<class 'pandas.core.series.Series'>


In [ ]:
# numpy
a = np.arange(12).reshape(3,4)
print(type(a))
print(a)
print(a[1][2])  # a[행][열]
print(a[1,2])   #a[행,열]


<class 'numpy.ndarray'>
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6
6


In [ ]:
# list
b = [1,2,3,4],[5,6,7,8],[9,10,11,12]
print(type(b))
print(b)
print(b[1][2])  #list에서 슬라이싱, boolean indexing, fancy indexing 안됨

<class 'tuple'>
([1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12])
7


In [ ]:
print(data)

   0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10


In [ ]:
#values()하면 numpy포맷으로 변환한다.
#내부적으로 numpy로 되어 있기 때문에 가능하다.
print(data.values)
print(type(data.values))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>


In [ ]:
# '__array__'가 있으면 numpy와 호환된다.
print(dir(data))

['T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__contains__', '__copy__', '__dataframe__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul_

## 웹 주소에서 데이터 불러오기

In [ ]:
# header는 기본이 첫줄을 컬럼명으로 가져오도록 설정이 되어 있기 때문에 header='infer' 생략 가능하다.
data = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv', header='infer')
data

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
# 전반적인 데이터 정보 확인
data.info() #실제 저장된 부분은 numpy

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object 
 3   smoker      244 non-null    object 
 4   day         244 non-null    object 
 5   time        244 non-null    object 
 6   size        244 non-null    int64  
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB


In [ ]:
#기본적으로 앞의 5개를 보여줌
data.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
# 안에 숫자 넣어주면 그 수만큼 출력
data.head(10)

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

In [ ]:
# 제일 아래에서 5개를 보여줌
data.tail()

total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [ ]:
# random으로 1개씩 보여줌
data.sample()

total_bill  tip     sex smoker   day   time  size
202        13.0  2.0  Female    Yes  Thur  Lunch     2

In [ ]:
data.sample(3)

total_bill   tip   sex smoker  day    time  size
216       28.15  3.00  Male    Yes  Sat  Dinner     5
62        11.02  1.98  Male    Yes  Sat  Dinner     2
49        18.04  3.00  Male     No  Sun  Dinner     2

In [ ]:
#데이터ㅓ만 가지고 옴
data.values

array([[16.99, 1.01, 'Female', ..., 'Sun', 'Dinner', 2],
       [10.34, 1.66, 'Male', ..., 'Sun', 'Dinner', 3],
       [21.01, 3.5, 'Male', ..., 'Sun', 'Dinner', 3],
       ...,
       [22.67, 2.0, 'Male', ..., 'Sat', 'Dinner', 2],
       [17.82, 1.75, 'Male', ..., 'Sat', 'Dinner', 2],
       [18.78, 3.0, 'Female', ..., 'Thur', 'Dinner', 2]], dtype=object)

In [ ]:
#index만 가지고 옴
data.index

RangeIndex(start=0, stop=244, step=1)

In [ ]:
#column만 가지고 옴
data.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [ ]:
#dict 타입
dicdata = {'name':'홍길동', 'age':30}

print(dicdata['name']) #  정상처리 홍길동
#print(dicdata.name)    #  오류발생 AttributeError: 'dict' object has no attribute 'name'

홍길동


In [ ]:
print(dir(dict))
print(dict.items)
print(dicdata.items())

['__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__ior__', '__iter__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__ror__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'clear', 'copy', 'fromkeys', 'get', 'items', 'keys', 'pop', 'popitem', 'setdefault', 'update', 'values']
<method 'items' of 'dict' objects>
dict_items([('name', '홍길동'), ('age', 30)])


In [ ]:
#pandas는 dictionary와 attribute 방식 모두 사용할 수 있다.
#dictionary 방식 이용
print(data['tip'])

#attribute 방식 이용
print(data.tip)

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64
0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64


In [ ]:
#컬럼을 fancying indexing을 이용해서 가져올 수 있으나 행을 이용해서 가져올 수 없다.
#print(data[['tip', 'day']]) # 열이 들어간다. 정상처리

# KeyError

#print(data[0,2])
# data.iloc[행]이므로 행의 fancying indexing을 사용할 수 있다.
print(data.iloc[[0,2]])   #정상처리

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
2       21.01  3.50    Male     No  Sun  Dinner     3


In [ ]:
# TypeError: cannot do slice indexing on RangeIndex with these indexers [tip] of type str

#컬럼을 slicing을 이용해서 가져올 수 없다.
#print(data['tip': 'day'])                #data[열이름] indexing

#row를 slicing을 이용해서 가져올 수 있다. # data[행이름:행이름] slicilng
print(data[1:3])

   total_bill   tip   sex smoker  day    time  size
1       10.34  1.66  Male     No  Sun  Dinner     3
2       21.01  3.50  Male     No  Sun  Dinner     3


하나의 컬럼 또는 행을 가져오면 Series를 리턴한다.

fancy indexing을 이용해서 하나의 컬럼 도는 행을 가져오면 DataFrame으로 리턴한다.

In [ ]:
print(type(data.iloc[3]))
print(data.iloc[3])

print(type(data['tip']))
print(data['tip'])

<class 'pandas.core.series.Series'>
total_bill     23.68
tip             3.31
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 3, dtype: object
<class 'pandas.core.series.Series'>
0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64


In [ ]:
#data[['tip', 'day']]   #DataFrame 타입으로 리턴
print(data.iloc[1:3])          #DataFrame 타입으로 리턴
print(data.iloc[1:3, :])

   total_bill   tip   sex smoker  day    time  size
1       10.34  1.66  Male     No  Sun  Dinner     3
2       21.01  3.50  Male     No  Sun  Dinner     3
   total_bill   tip   sex smoker  day    time  size
1       10.34  1.66  Male     No  Sun  Dinner     3
2       21.01  3.50  Male     No  Sun  Dinner     3


In [ ]:
data.iloc[0:5, 1:3]  #data.iloc[행의 index, 열의 index]

tip     sex
0  1.01  Female
1  1.66    Male
2  3.50    Male
3  3.31    Male
4  3.61  Female

In [ ]:
print(data.iloc[[0,3,5], [1,3,4]])
print(data.iloc[[0,3,5], [1,3,4]])


    tip smoker  day
0  1.01     No  Sun
3  3.31     No  Sun
5  4.71     No  Sun
    tip smoker  day
0  1.01     No  Sun
3  3.31     No  Sun
5  4.71     No  Sun


In [ ]:
print(data.iloc[3][1])    #3행 1열
print(data.iloc[3,1])     #3행 1열

3.31
3.31


In [ ]:
data.sample(3)

total_bill   tip   sex smoker   day    time  size
43        9.68  1.32  Male     No   Sun  Dinner     2
61       13.81  2.00  Male    Yes   Sat  Dinner     2
80       19.44  3.00  Male    Yes  Thur   Lunch     2

iloc는 번호를 이용해서 가져오고, loc는 이름을 이용해서 가져온다.

In [ ]:
data.loc[0,'tip']    #data.loc[행이름, 열이름]

1.01

In [ ]:
data.iloc[0,1]   #data.iloc[행번호,열번호]

1.01

In [ ]:
data['tip'][0]     #data[열이름][행이름]  #data[행이름:행이름][열이름:열이름]

1.01

In [ ]:
data.loc[0:3, 'tip':'day']

tip     sex smoker  day
0  1.01  Female     No  Sun
1  1.66    Male     No  Sun
2  3.50    Male     No  Sun
3  3.31    Male     No  Sun

In [ ]:
data.iloc[0:3, 1:5]

tip     sex smoker  day
0  1.01  Female     No  Sun
1  1.66    Male     No  Sun
2  3.50    Male     No  Sun

In [ ]:
data.loc[0,3,5],['tip','day','time']

IndexingError: ignored

In [ ]:
data.iloc[[0,3,5], [1,4,5]]

tip  day    time
0  1.01  Sun  Dinner
3  3.31  Sun  Dinner
5  4.71  Sun  Dinner

### at

이름으로 한 위치의 값만 가져온다.

In [ ]:
print(data.at[0,'tip'])   #ok
print(data.loc[0,'tip'])  #ok
print(data.iloc[0,1])     #ok
print(data['tip'][0])     #ok

#print(data.at[0]['tip']) TypeError
print(data.loc[0]['tip']) #ok
print(data.iloc[0][1])    #ok

print(data['tip'])        #열(이름)
print(data[3:5])          #행(번호)

1.01
1.01
1.01
1.01
1.01
1.01
0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64
   total_bill   tip     sex smoker  day    time  size
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4


In [ ]:
#at은 slicing을 사용할 수 없다
#InvalidIndexError
data.at[0:3, 'tip']

InvalidIndexError: ignored

In [ ]:
#at은 fancy indexing을 사용할 수 없다
#InvalidIndexError
#data.at[[0,1,5], 'tip']

#열일때
#data[['tip', 'day']] #ok
#data['tip', 'day']   #TypeError

#행일때
data[0:5]                 #ok
#data[[0,1,3]]           #KeyError


total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

##iat

iat는 번호로 한 위치의 값을 가져온다.

In [ ]:
print(data.iat[0,1])
print(data.at[0,'tip'])

1.01
1.01


In [ ]:
# iat, at은 slicing을 사용할 수 없다.
data.lat[[0,3],1]

#iat, at은 fancy indexing을 사용할 수 없다.

AttributeError: ignored

boolean indexing

In [ ]:
data.tip>=5
data[['tip']>=5]

TypeError: ignored

In [ ]:
data[data['tip'] >=5]['tip']

11      5.00
23      7.58
39      5.00
44      5.60
46      5.00
47      6.00
52      5.20
59      6.73
73      5.00
83      5.00
85      5.17
88      5.85
116     5.07
141     6.70
142     5.00
143     5.00
155     5.14
156     5.00
170    10.00
172     5.15
181     5.65
183     6.50
185     5.00
197     5.00
211     5.16
212     9.00
214     6.50
239     5.92
Name: tip, dtype: float64

In [ ]:
data[data['tip'] >=5].loc[:, 'tip':'day']

tip     sex smoker   day
11    5.00  Female     No   Sun
23    7.58    Male     No   Sat
39    5.00    Male     No   Sat
44    5.60    Male     No   Sun
46    5.00    Male     No   Sun
47    6.00    Male     No   Sun
52    5.20  Female     No   Sun
59    6.73    Male     No   Sat
73    5.00  Female    Yes   Sat
83    5.00    Male    Yes  Thur
85    5.17  Female     No  Thur
88    5.85    Male     No  Thur
116   5.07    Male     No   Sun
141   6.70    Male     No  Thur
142   5.00    Male     No  Thur
143   5.00  Female     No  Thur
155   5.14  Female     No   Sun
156   5.00    Male     No   Sun
170  10.00    Male    Yes   Sat
172   5.15    Male    Yes   Sun
181   5.65    Male    Yes   Sun
183   6.50    Male    Yes   Sun
185   5.00    Male     No   Sun
197   5.00  Female    Yes  Thur
211   5.16    Male    Yes   Sat
212   9.00    Male     No   Sat
214   6.50  Female    Yes   Sat
239   5.92    Male     No   Sat

In [ ]:
data[data['tip']>=5].iloc[:, 1:5]

tip     sex smoker   day
11    5.00  Female     No   Sun
23    7.58    Male     No   Sat
39    5.00    Male     No   Sat
44    5.60    Male     No   Sun
46    5.00    Male     No   Sun
47    6.00    Male     No   Sun
52    5.20  Female     No   Sun
59    6.73    Male     No   Sat
73    5.00  Female    Yes   Sat
83    5.00    Male    Yes  Thur
85    5.17  Female     No  Thur
88    5.85    Male     No  Thur
116   5.07    Male     No   Sun
141   6.70    Male     No  Thur
142   5.00    Male     No  Thur
143   5.00  Female     No  Thur
155   5.14  Female     No   Sun
156   5.00    Male     No   Sun
170  10.00    Male    Yes   Sat
172   5.15    Male    Yes   Sun
181   5.65    Male    Yes   Sun
183   6.50    Male    Yes   Sun
185   5.00    Male     No   Sun
197   5.00  Female    Yes  Thur
211   5.16    Male    Yes   Sat
212   9.00    Male     No   Sat
214   6.50  Female    Yes   Sat
239   5.92    Male     No   Sat

In [ ]:
#data['tip'][0] #출력되는 것을 잡아서 series라 부른다
data[0:1]

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2

요일이 'Sun' 이거나 'Sat'의 'tip'과 'day'의 값을 가져오기


In [ ]:
data['day']=='Sun'
data['day']=='Sat'

rs = data[(data['day']=='Sun') | (data['day']=='Sat')]
rs['day'].unique()

rs[['tip','day']]

data[(data['day']=='Sun') | (data['day']=='Sat')][['tip','day']]

tip  day
0    1.01  Sun
1    1.66  Sun
2    3.50  Sun
3    3.31  Sun
4    3.61  Sun
..    ...  ...
238  4.67  Sat
239  5.92  Sat
240  2.00  Sat
241  2.00  Sat
242  1.75  Sat

[163 rows x 2 columns]

In [ ]:
data.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [ ]:
print(data.columns)

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')


In [ ]:
print(dir(data))

['T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__contains__', '__copy__', '__dataframe__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul_

In [ ]:
data.shape

(244, 7)

In [ ]:
data.size # 승인 대상도 정해줘야 되는구나.

1708

In [ ]:
data['size']

0      2
1      3
2      3
3      2
4      4
      ..
239    3
240    2
241    2
242    2
243    2
Name: size, Length: 244, dtype: int64

In [ ]:
#컬럼명을 바꿀 때 mapper, columns 옵션을 이용해서 변경할 수 있다.
data2 = data.rename(mapper={'size':'size_'}, axis=1)  #행을 바꾸겠다 axis=0 열을 바꾸겠다 axis=1 ㄷㄷ
data2 = data.rename(columns={'size':'size_'})
data2

total_bill   tip     sex smoker   day    time  size_
0         16.99  1.01  Female     No   Sun  Dinner      2
1         10.34  1.66    Male     No   Sun  Dinner      3
2         21.01  3.50    Male     No   Sun  Dinner      3
3         23.68  3.31    Male     No   Sun  Dinner      2
4         24.59  3.61  Female     No   Sun  Dinner      4
..          ...   ...     ...    ...   ...     ...    ...
239       29.03  5.92    Male     No   Sat  Dinner      3
240       27.18  2.00  Female    Yes   Sat  Dinner      2
241       22.67  2.00    Male    Yes   Sat  Dinner      2
242       17.82  1.75    Male     No   Sat  Dinner      2
243       18.78  3.00  Female     No  Thur  Dinner      2

[244 rows x 7 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object 
 3   smoker      244 non-null    object 
 4   day         244 non-null    object 
 5   time        244 non-null    object 
 6   size        244 non-null    int64  
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB


### category
 - category는 문자열(object)보다 더 많은 기능을 할 수 있다.
 - category는 문자 또는 숫자도 가능하다.
 - category는 몇 개롤 분류할 수 있을 때 발생한다. ex)성별(남,여)


In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       2 non-null      int64
 1   1       2 non-null      int64
 2   2       2 non-null      int64
 3   3       2 non-null      int64
 4   4       2 non-null      int64
dtypes: int64(5)
memory usage: 208.0 bytes


In [ ]:
print(data['sex'].dtype)

object


In [ ]:
data['sex'] = data['sex'].astype('category') #astype: type 변경 sex의 데이터타입을 object에서 category로 변경해서 data['sex']에 적용된다.

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object 
 3   smoker      244 non-null    object 
 4   day         244 non-null    object 
 5   time        244 non-null    object 
 6   size        244 non-null    int64  
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB


In [ ]:
data[data['sex']=='Female']['sex'].unique()

['Female']
Categories (2, object): ['Female', 'Male']

금요일에 온 여자만 가져오기

In [ ]:
data['day']=='Fri'
data['sex']=='Female'

rs = data[(data['day']=='Fri') | (data['sex']=='Female')]
rs['day'].unique()

rs[['sex','day']]

data[(data['day']=='Fri')][['sex','day']]

sex  day
90     Male  Fri
91     Male  Fri
92   Female  Fri
93   Female  Fri
94   Female  Fri
95     Male  Fri
96     Male  Fri
97     Male  Fri
98     Male  Fri
99     Male  Fri
100  Female  Fri
101  Female  Fri
220    Male  Fri
221  Female  Fri
222    Male  Fri
223  Female  Fri
224    Male  Fri
225  Female  Fri
226  Female  Fri

In [ ]:
data[data['day']=='Fri']['day'].unique()
data[data['sex']=='Female']['sex'].unique()
data[(data['day']=='Fri') & (data['sex']=='Female')]['sex'].unique()
data[(data['day']=='Fri') & (data['sex']=='Female')]['day'].unique()

data[(data['day']=='Fri') & (data['sex']=='Female')]

total_bill   tip     sex smoker  day    time  size
92         5.75  1.00  Female    Yes  Fri  Dinner     2
93        16.32  4.30  Female    Yes  Fri  Dinner     2
94        22.75  3.25  Female     No  Fri  Dinner     2
100       11.35  2.50  Female    Yes  Fri  Dinner     2
101       15.38  3.00  Female    Yes  Fri  Dinner     2
221       13.42  3.48  Female    Yes  Fri   Lunch     2
223       15.98  3.00  Female     No  Fri   Lunch     3
225       16.27  2.50  Female    Yes  Fri   Lunch     2
226       10.09  2.00  Female    Yes  Fri   Lunch     2

## describe
 - describe는 기초적인 통계분석을 해주는 함수이다.

In [ ]:
#describ()의 기본은 데이터가 숫자로 된 컬럼만 가져온다.
data.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [ ]:
type(data.describe())

pandas.core.frame.DataFrame

In [ ]:
#pandas는 numpy기반이라서 numpy 기능을 사용할 수 있다.
#데이터 타입이 object일 때만 가져온다.
data.describe(include=['object'])
data.describe(include=['O'])   #대문자 알파벳 O

smoker  day    time
count     244  244     244
unique      2    4       2
top        No  Sat  Dinner
freq      151   87     176

In [ ]:
data.describe(include=[np.number]) #숫자 모두 (float64, int64,...)
data.describe(include=['float64']) #숫자중에 데이터타입이 float64

total_bill         tip
count  244.000000  244.000000
mean    19.785943    2.998279
std      8.902412    1.383638
min      3.070000    1.000000
25%     13.347500    2.000000
50%     17.795000    2.900000
75%     24.127500    3.562500
max     50.810000   10.000000

In [ ]:
data.describe(include='all')

total_bill         tip   sex smoker  day    time        size
count   244.000000  244.000000   244    244  244     244  244.000000
unique         NaN         NaN     2      2    4       2         NaN
top            NaN         NaN  Male     No  Sat  Dinner         NaN
freq           NaN         NaN   157    151   87     176         NaN
mean     19.785943    2.998279   NaN    NaN  NaN     NaN    2.569672
std       8.902412    1.383638   NaN    NaN  NaN     NaN    0.951100
min       3.070000    1.000000   NaN    NaN  NaN     NaN    1.000000
25%      13.347500    2.000000   NaN    NaN  NaN     NaN    2.000000
50%      17.795000    2.900000   NaN    NaN  NaN     NaN    2.000000
75%      24.127500    3.562500   NaN    NaN  NaN     NaN    3.000000
max      50.810000   10.000000   NaN    NaN  NaN     NaN    6.000000

In [ ]:
#day컬럼의 요소갯수 244개
print(len(data['day'].values))
print(data['day'].values.size)

244
244


In [ ]:
# unique()은 컬럼의 고유값을 리턴해준다.(Series만 사용한다.)
print(data['day'].unique())
print(data['day'].value_counts()) #value_counts()는 unique값과 갯수를 리턴해준다.(Series만 사용한다.)

['Sun' 'Sat' 'Thur' 'Fri']
Sat     87
Sun     76
Thur    62
Fri     19
Name: day, dtype: int64


주말고객수와 평일 고객수를 구하기


In [ ]:
data['day'].value_counts() #요일 고객수
data((data['day']=='Sat') | (data['day']=='Sun')).value_counts()

TypeError: ignored

In [ ]:
data['day'].isin({'Sat','Sun'}).value_counts()

where

In [ ]:
a = np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [ ]:
#where의 인자는 조건이다.
# 조건만 넣을 경우 True의 위치를 리턴한다.
np.where(a>30)

(array([3, 4]),)

In [ ]:
# where의 인자 개수에 따라서 기능이 달라진다.
# 조건이 True이면 0, False이면 100을 리턴한다
np.where(a>30, 0, 100) # np.where(조건, 참일 경우의 값, 거짓일 경우의 값)

array([100, 100, 100,   0,   0])

### describe() 결과를 pandas에서 제공하는 함수

In [ ]:
data.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [ ]:
data['tip'].mean()

2.99827868852459

In [ ]:
data['tip'].min()

1.0

In [ ]:
data['tip'].max()

10.0

In [ ]:
data['tip'].std()

1.3836381890011822

### describe()결과를 numpy에서 제공하는 함수

In [ ]:
import numpy.ma as ma

In [ ]:
# data에서 'tip'칼럼의 값만을 가져온다.
kk = data.values[:, 1].copy()
kk

array([1.01, 1.66, 3.5, 3.31, 3.61, 4.71, 2.0, 3.12, 1.96, 3.23, 1.71,
       5.0, 1.57, 3.0, 3.02, 3.92, 1.67, 3.71, 3.5, 3.35, 4.08, 2.75,
       2.23, 7.58, 3.18, 2.34, 2.0, 2.0, 4.3, 3.0, 1.45, 2.5, 3.0, 2.45,
       3.27, 3.6, 2.0, 3.07, 2.31, 5.0, 2.24, 2.54, 3.06, 1.32, 5.6, 3.0,
       5.0, 6.0, 2.05, 3.0, 2.5, 2.6, 5.2, 1.56, 4.34, 3.51, 3.0, 1.5,
       1.76, 6.73, 3.21, 2.0, 1.98, 3.76, 2.64, 3.15, 2.47, 1.0, 2.01,
       2.09, 1.97, 3.0, 3.14, 5.0, 2.2, 1.25, 3.08, 4.0, 3.0, 2.71, 3.0,
       3.4, 1.83, 5.0, 2.03, 5.17, 2.0, 4.0, 5.85, 3.0, 3.0, 3.5, 1.0,
       4.3, 3.25, 4.73, 4.0, 1.5, 3.0, 1.5, 2.5, 3.0, 2.5, 3.48, 4.08,
       1.64, 4.06, 4.29, 3.76, 4.0, 3.0, 1.0, 4.0, 2.55, 4.0, 3.5, 5.07,
       1.5, 1.8, 2.92, 2.31, 1.68, 2.5, 2.0, 2.52, 4.2, 1.48, 2.0, 2.0,
       2.18, 1.5, 2.83, 1.5, 2.0, 3.25, 1.25, 2.0, 2.0, 2.0, 2.75, 3.5,
       6.7, 5.0, 5.0, 2.3, 1.5, 1.36, 1.63, 1.73, 2.0, 2.5, 2.0, 2.74,
       2.0, 2.0, 5.14, 5.0, 3.75, 2.61, 2.0, 3.5, 2.5, 2.0, 2.0, 3.

In [ ]:
xx = ma.array(data.values[:, 1])
xx

masked_array(data=[1.01, 1.66, 3.5, 3.31, 3.61, 4.71, 2.0, 3.12, 1.96,
                   3.23, 1.71, 5.0, 1.57, 3.0, 3.02, 3.92, 1.67, 3.71,
                   3.5, 3.35, 4.08, 2.75, 2.23, 7.58, 3.18, 2.34, 2.0,
                   2.0, 4.3, 3.0, 1.45, 2.5, 3.0, 2.45, 3.27, 3.6, 2.0,
                   3.07, 2.31, 5.0, 2.24, 2.54, 3.06, 1.32, 5.6, 3.0, 5.0,
                   6.0, 2.05, 3.0, 2.5, 2.6, 5.2, 1.56, 4.34, 3.51, 3.0,
                   1.5, 1.76, 6.73, 3.21, 2.0, 1.98, 3.76, 2.64, 3.15,
                   2.47, 1.0, 2.01, 2.09, 1.97, 3.0, 3.14, 5.0, 2.2, 1.25,
                   3.08, 4.0, 3.0, 2.71, 3.0, 3.4, 1.83, 5.0, 2.03, 5.17,
                   2.0, 4.0, 5.85, 3.0, 3.0, 3.5, 1.0, 4.3, 3.25, 4.73,
                   4.0, 1.5, 3.0, 1.5, 2.5, 3.0, 2.5, 3.48, 4.08, 1.64,
                   4.06, 4.29, 3.76, 4.0, 3.0, 1.0, 4.0, 2.55, 4.0, 3.5,
                   5.07, 1.5, 1.8, 2.92, 2.31, 1.68, 2.5, 2.0, 2.52, 4.2,
                   1.48, 2.0, 2.0, 2.18, 1.5, 2.83, 1.5,

In [ ]:
print(dir(xx))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__div__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__idiv__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', 

In [ ]:
xx.count()

244

In [ ]:
xx.count()

244

In [ ]:
xx.mean()

2.9982786885245902

In [ ]:
ma.mean(xx) #평균

2.9982786885245902

https://wikidocs.net/159927

참고 사이트