<a href="https://colab.research.google.com/github/onsoon829/dataproject/blob/master/650_%EC%9E%90%EC%97%B0%EC%96%B4%EC%B2%98%EB%A6%AC_%EC%9E%84%EB%B2%A0%EB%94%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

%cd  '/content/drive/MyDrive/ai_chat_python'

Mounted at /content/drive
/content/drive/MyDrive/ai_chat_python


In [ ]:
!pip install konlpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 57.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 465.3/465.3 kB 38.8 MB/s eta 0:00:00


## 단어 임베딩
 - 단어 임베딩은 말뭉치에서 각각의 단어를 벡터로 변환하는 기법이다.

 https://velog.io/@hotsun1508/NLP-Word-Embedding

1.1 원 핫 인코딩

In [ ]:
from konlpy.tag import Komoran
import numpy as np

komoran = Komoran()
text = "오늘 날씨는 구름이 많아요."

# 명사만 추출
nouns = komoran.nouns(text)
print(nouns)

# 단어 사전 구축 및 단어별 인덱스 부여
dics = {}
for word in nouns: # ['오늘', '날씨', '구름']
    if word not in dics.keys():
        dics[word] = len(dics)
print(dics)

# 원-핫 인코딩
nb_classes = len(dics)
targets = list(dics.values())
one_hot_targets = np.eye(nb_classes)[targets]
print(one_hot_targets)

['오늘', '날씨', '구름']
{'오늘': 0, '날씨': 1, '구름': 2}
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1_2 희소표현과 분산표현
 - 원-핫 인코딩은 표현하고자 하는 단어의 인덱스 요소만 1이고 나머지 요소는 모두 0으로 표현되는 희소 벡터(또는 희소행렬)이다.이처럼 단어가 희소 벡터로 표현되는 방식을 희소표현(sparse representation)이라 부른다.
  - 희소표현은 각각의 차원이 독립적인 정보를 지니고 있어 사람이 이해하기에 직관적인 장점이 있지만, 단어 사전의 크기가 커질수록 메모리낭비와 계산 복잡도가 커지는 단점이 있다.
 - 또한 단어 간의 연관성이 전혀 없어 의미를 담을 수 없다.
 - 자연어 처리를 잘하기 위해서는 기본 토큰이 되는 단어의 의미와 주변단어간의 관계가 단어 임베딩에 표현되어야 한다. 하지만 희소표현의 경우 그러지 못하다. 이를 해결하기 위해서 각 단어 간의 유사성을 잘 표현하면서도 벡터 공간을 절약할 수 있는 방법을 고안했는데, 이를 분산표현(distributed representation)이라 한다.
 - 분산표현은 한 단어의 정보가 특정 차원에 표현되지 않고 여러 차원에 분산되어 표현된다하여 붙여진 이름이다. 즉, 하나의 차원에 다양한 정보를 가지고 있다. 예로 색상을 표현하는 RGB 모델은 3차원 형태의 벡터로 생각할 수 있으며 분산표현 방식이다. 연두색은 RGB(204,255,204)형태로 분산 표현을 하는 것이다.
 - 분산 표현은 우리가 원하는 차원에 데이터를 최대한 밀집시킬 수 있어 밀집표현(dense representation)이라고 부르며, 밀집표현으로 만들어진 벡터를 밀집벡터(dense vector)라 한다.